server:
  port: 9021

spring:
  application:
    name: books-service

  datasource:
    url: jdbc:mariadb://j8b201.p.ssafy.io:3310/girin_books
    username: 'developer'
    password: 'j8b201'
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB